os: linux
dist: jammy

language: java

before_install:
  - sudo apt-get -m install openjdk-11-jdk libltdl-dev curl;
  - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64;
  - export PATH=$JAVA_HOME/bin:$PATH;
  - mkdir $HOME/local
  - export PATH=$HOME/local/bin:$PATH
  - curl -o autoconf-2.71.tar.gz https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.gz
  - tar xzvf autoconf-2.71.tar.gz
  - cd autoconf-2.71; ./configure --prefix $HOME/local; make; make install; cd ..

install:
  - export APACHE_ANT_BASE=$(curl http://apache.mirror.iphh.net/ant/binaries/ | grep "apache-ant-1.9..*-bin.tar.gz" | tail -1 | sed  's/.*href="\([^"]*\)-bin.tar.gz".*/\1/g')
  - 'echo "Apache Ant ARCHIVE: $APACHE_ANT_BASE"'
  - 'wget http://apache.mirror.iphh.net/ant/binaries/$APACHE_ANT_BASE-bin.tar.gz && tar xzf $APACHE_ANT_BASE-bin.tar.gz && sudo mv $APACHE_ANT_BASE /usr/local/$APACHE_ANT_BASE && sudo rm -f /usr/local/ant && sudo ln -s /usr/local/$APACHE_ANT_BASE /usr/local/ant && sudo ln -s /usr/local/$APACHE_ANT_BASE/bin/ant /usr/local/bin/ant || true'
  - 'sudo apt-get -y install texinfo || true'

script:
  - ant test
  - ant test-platform

jobs:
  include:
    - name: "Linux JDK11 ARM"
      arch: arm64
